name: Sanity Trigger Rebuild

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [sanity-update, build, webhook, sanity]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge Rebuild
        run: echo "Code or Sanity content change received. Rebuild triggered."
